### ISSUE TITLE
Check storage status on news.mla.hcommons.org

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#746]
From Anatole: 

We've been running into an issue while trying to publish a high-profile news item on news.mla.hcommons.org. Each time I try to upload an image, I get an error message that says "This file could not be moved." The images are a size that we've uploaded before (300x300) and are well below the recommended size for files for the posts. Anna and I have tried a variety of different changes (uploading a jpeg instead of png, opening a new Chrome window, creating a new draft, renaming the photos, etc.) that haven't worked.

Can we check how much storage the news site has used? This looks like a storage issue to me.

**Comment by mikethicke** [comment]
This should be working now. There's something wonky with the file and directory permissions with these legacy MLA sites and I'm not sure what's causing it. So it might recur in the future. This is a monthly thing, so I'm going to check on Nov 1 to see what the status us.

**Comment by bjr70** [comment]
Notified user. Thanks Mike!

**Comment by bjr70** [comment]
User still having the same issue. From Anatole: Hi everyone, I hope you're well! I just heard that an MLA staff member (cbaer on the Commons) is having the same issue from October 17 where she can't upload images to news.mla.hcommons.org. Could that be an issue with the site storage limit?

**Comment by rekmla** [comment]
@bonnie, @mikethicke - the MLA files problem is a server permissions problem. Each user site has year and month sub directories that store uploaded files. These directories are created on the fly as needed. In the past, the directories were created with the www-data user as the owner and now they are being created with the ubuntu user as the owner. This is probably due to a recent OS or web server change. I'm setting the permissions on the November directory as the issue is important to a news release.

ubuntu@hcommons:/srv/www/commons/shared/blogs.dir/11/files/2023$ ls -l
total 44
drwxrwx--- 2 www-data www-data 6144 Jan  1  2023 01
drwxrwx--- 2 www-data www-data 6144 Feb  1  2023 02
drwxrwx--- 2 www-data www-data 6144 Mar  1  2023 03
drwxrwx--- 2 www-data www-data 6144 Apr  1  2023 04
drwxrwx--- 2 www-data www-data 6144 May  1  2023 05
drwxrwx--- 2 www-data www-data 6144 Jun  1 00:11 06
drwxrwx--- 2 www-data www-data 6144 Jul  1 00:35 07
drwxrwx--- 2 www-data www-data 6144 Aug  1 00:14 08
drwxrwx--- 2 www-data www-data 6144 Sep  1 01:17 09
drwxrwx--- 2 ubuntu   ubuntu   6144 Oct  3 01:13 10
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 11

**Comment by rekmla** [comment]
Certainly strange since the problem is confined to blogs.dir (legacy sites) and does not appear to be a problem in sites.

**Comment by rekmla** [comment]
Sorry, wrong site for news. Site is 15, not 11.

ubuntu@hcommons:/srv/www/commons/shared/blogs.dir/15/files/2023$ ls -l
total 44
drwxrwx--- 2 www-data www-data 6144 Oct 17 17:54 01
drwxrwx--- 2 www-data www-data 6144 Feb  1  2023 02
drwxrwx--- 2 www-data www-data 6144 Mar  1  2023 03
drwxrwx--- 2 www-data www-data 6144 Apr  1  2023 04
drwxrwx--- 2 www-data www-data 6144 May  1  2023 05
drwxrwx--- 2 www-data www-data 6144 Jun  1 00:41 06
drwxrwx--- 2 www-data www-data 6144 Jul  1 00:43 07
drwxrwx--- 2 www-data www-data 6144 Aug 15 14:55 08
drwxrwx--- 2 www-data www-data 6144 Sep  1 01:17 09
drwxrwx--- 2 www-data www-data 6144 Oct 18 18:07 10
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 11
ubuntu@hcommons:/srv/www/commons/shared/blogs.dir/15/files/2023$ sudo chown www-data:www-data 11

**Comment by rekmla** [comment]
Certainly odd that some are okay (owned by www-data).
I think these should be fixed even if the majority will not get files created this month.

```ubuntu@hcommons:/srv/www/commons/shared/blogs.dir$ ls -ld1 */files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 1000381/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 1000382/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 1000384/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 1000393/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 1000399/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 1000402/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 1000403/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 1000405/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:10 1000407/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:10 1000409/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:10 1000412/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:10 1000415/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:10 1000416/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:10 1000425/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 00:11 1000434/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:11 1000449/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 1000454/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 1000455/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:11 1000465/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:11 1000474/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:11 1000478/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000491/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000492/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000496/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000498/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000504/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000508/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000509/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000510/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000512/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000513/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000514/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:12 1000515/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:14 1000556/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:14 1000563/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:14 1000564/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:14 1000582/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:15 1000597/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:15 1000613/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:15 1000617/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 00:01 1000642/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 1000668/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 1000677/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:15 1000835/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 02:06 1000993/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 04:35 1001303/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 09:03 1001366/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:13 1002691/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov 11 02:28 1003064/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 100/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 101/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 102/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 103/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 105/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 106/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 107/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 109/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 10/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 110/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:11 111/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 112/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:11 113/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 114/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 115/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 117/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 118/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 119/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 01:09 11/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 120/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 121/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 122/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 123/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 124/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 125/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 126/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:11 127/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 128/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 129/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 130/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 131/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 132/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 133/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 134/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:10 135/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 136/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 137/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 138/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 139/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 13/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 140/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 141/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 142/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 143/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 145/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 146/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:06 147/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 148/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 149/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 14/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 150/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 152/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 153/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 154/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 155/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 156/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 157/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 158/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:09 159/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov 14 19:40 15/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:09 160/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 161/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:09 162/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 163/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 164/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 166/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 04:02 168/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 172/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 173/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 175/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 176/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 177/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 179/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 17/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 180/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 181/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 182/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 183/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 184/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 185/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 187/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:08 188/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 18/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 191/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:08 192/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:05 193/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 194/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 196/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 197/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:07 198/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:08 199/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 200/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 203/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 00:07 204/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 205/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 206/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 208/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 209/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  6 01:09 20/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 210/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 211/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 212/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 213/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 214/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  4 01:07 215/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 217/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 218/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 219/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 21/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 220/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 04:02 221/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 223/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 224/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 225/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 226/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 228/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:04 229/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 22/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 231/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 232/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 233/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 234/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 235/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 236/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 238/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 239/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 23/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 240/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 241/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 242/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 243/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 244/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:02 245/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 04:08 246/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 247/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 05:26 248/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 249/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 24/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 254/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 255/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:02 256/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 257/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 258/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 259/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 260/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 261/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 262/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 263/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 264/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 266/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 267/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 269/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 270/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 271/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 272/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 273/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 274/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 275/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 276/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 277/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:02 278/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:03 279/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 280/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 281/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 04:25 282/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 285/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 286/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 04:28 287/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:01 288/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 289/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 290/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 291/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 04:01 292/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 293/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 294/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:01 296/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 297/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 16:42 298/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 04:15 2/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 300/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:01 301/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 302/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 304/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:02 305/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 306/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 307/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 308/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:01 309/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 312/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 00:13 313/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 314/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 315/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:01 316/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:01 317/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 318/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 319/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 00:40 320/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 321/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 322/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 323/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 324/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:00 325/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:01 326/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 327/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 329/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 330/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 331/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 333/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 334/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 336/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 337/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 338/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 339/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 340/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 342/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 344/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 345/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 16:11 346/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 348/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 349/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 34/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 350/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 351/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  3 01:00 352/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 353/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 355/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 356/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 357/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 358/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 359/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 35/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:00 360/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 36/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 37/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 38/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 39/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 40/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 41/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 42/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 43/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 44/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 46/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 47/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 48/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 49/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 50/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 53/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 54/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 55/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 56/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 57/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 58/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 59/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 60/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 61/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 62/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 63/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  6 01:08 64/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  6 01:07 67/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  6 01:07 69/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:09 6/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 71/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 72/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 73/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 00:11 75/files/2023/11
drwxrwx--- 2 www-data www-data 6144 Nov  1 00:02 76/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 78/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 79/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 80/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:08 81/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 82/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 83/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 84/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 85/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 86/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 87/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  6 01:06 88/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  6 01:07 89/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 90/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 91/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 92/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 93/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 94/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 95/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 96/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 97/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 98/files/2023/11
drwxrwx--- 2 ubuntu   ubuntu   6144 Nov  1 01:07 99/files/2023/11
ubuntu@hcommons:/srv/www/commons/shared/blogs.dir$

**Comment by rekmla** [comment]
@bjr70 So, there is a series of communication updates happening across the mla blogs. I don't really want to do a mass update without your ack.
I also don't want to continue logging in to do one off updates.

**Comment by mikethicke** [comment]
When Bonnie first opened the issue I changed the ownership of files and directories in blogs.dir to match that of the rest of the uploads folder and that addressed the immediate issue. 

I agree that to fix the immediate issue the same should be done again. (ie. a recursive chown)

I am bewildered why new folders in the uploads/sites directories are owned by www-data while new directories in blogs.dir are owned by ubuntu.

**Comment by bjr70** [comment]
> @bjr70 So, there is a series of communication updates happening across the mla blogs. I don't really want to do a mass update without your ack. I also don't want to continue logging in to do one off updates.

@rekmla yes, we should go ahead and do that. Much appreciated.

**Comment by rekmla** [comment]
Okay. All set for the month, I hope.
Since the problem is limited to one directory tree, it's probably not the web server user.
The original tree starts at the directory blogs.dir - which is currently owned by ubuntu
The new tree starts at uploads/sites - which is currently owned by www-data

MLA Original network path
/srv/www/commons/shared/blogs.dir/15/files/2023/11

HC Other new network path
/srv/www/commons/shared/uploads/sites/1003602/2023/11

Is it possible that items in /srv/www/commons/shared got ownership reset at some point in the recent past?
The fix might be as simple as setting the owner of blogs.dir to be www-data
It's worth checking dev staging sites to see if blogs.dir is owned by www-data

Anyway, that's my input on the issue.

**Comment by mikethicke** [comment]
I think this might be related to a cron job I added recently that was running WP CLI as ubuntu rather than www-data. If it ran at the wrong time it might inadvertently trigger the creation of a new monthly uploads folder owned by ubuntu? I don't know if this is the case but it's the only explanation I can think of for why new directories might be owned by ubuntu. I have fixed that job to run as www-data.

Why would this seemingly affect only subdirectories of blogs.dir? It shouldn't but maybe that was just random chance, or perhaps there is some other commonality with older MLA blogs that cause folders to be created in circumstances where they aren't for new blogs. Or perhaps it's because WP CLI runs on the MLA network by default?

I also changed the ownership of blogs.dir to www-data. I don't think that's the cause but it can't hurt.

**Comment by mikethicke** [comment]
Directories under blogs.dir that were created today (Feb 1) have the correct ownership (www-data). Closing.
