### ISSUE TITLE
Containerized WordPress production testing

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#873]
Issues related to the testing of the containerized WP for the Commons.

**Comment by babaklar** [comment]
I'm having an issue loading HASTAC groups. When I go to the Groups directory, I get the below error message for all the HASTAC specific groups. When I refresh the page, it seems to resolve the error. However, at times it still appears after reloading the page. This looks specific to HASTAC groups and not replicable on the other group directories across the Commons. 

Additionally, after creating a sample group, it is sometimes it is showing up here and sometimes it isn't. 
<img width="1437" alt="Screenshot 2024-05-08 at 9 59 58 AM" src="https://github.com/MESH-Research/commons/assets/103450846/11c41e26-3e6c-4737-b216-d26c88a08bc0">

**Comment by babaklar** [comment]
HASTAC CORE is not loading. This might not matter because of KC Works but still flagging here. CORE on other Commonses seems okay. 
<img width="1439" alt="Screenshot 2024-05-08 at 10 06 10 AM" src="https://github.com/MESH-Research/commons/assets/103450846/3cd3b504-b1ce-41c7-b9e9-7600d88a0afd">

**Comment by babaklar** [comment]
There is a slight functionality issue I'm experiencing on the Sites page that affects toggling between "All Sites" and "My Sites." At times, instead of showing all sites, it is showing what should be listed as "My Sites" instead. Double clicking on All Sites fixes the issue. 
<img width="1437" alt="Screenshot 2024-05-08 at 10 10 00 AM" src="https://github.com/MESH-Research/commons/assets/103450846/a098b8dd-9fd6-407e-849f-4dcf0962e605">

**Comment by babaklar** [comment]
I am not able to edit my sample group site or manage my group's settings. I created a site when I made the group, but when I select "Site" from the group page, it takes me to the hcommons.org homepage. When I go to "Manage" on the group's menu, I get the following Wordpress error. I was able to duplicate this error on both HASTAC and HCommons. 
<img width="1438" alt="Screenshot 2024-05-08 at 10 19 20 AM" src="https://github.com/MESH-Research/commons/assets/103450846/6602a13e-bd45-463c-bc9e-759731b6037c">

**Comment by babaklar** [comment]
Was able to duplicate the above issue with group settings and site on hcommons.org. The same thing happens with both of these issues.

**Comment by babaklar** [comment]
In my sample group, I am not able to upload or view files. Similar to what Bonnie reported, all groups with files show a number on the groups nav menu, but when I click on the page, there is nothing listed. This is what it looks like for me, and I cannot upload files here either. 

<img width="1439" alt="Screenshot 2024-05-08 at 10 33 07 AM" src="https://github.com/MESH-Research/commons/assets/103450846/8a90c094-e52c-4504-a41b-f2502d54d637">

This same issue occurs for me on HASTAC group docs. I'm having a different issue with HCommons docs I will add a different comment for. 

<img width="1439" alt="Screenshot 2024-05-08 at 10 40 47 AM" src="https://github.com/MESH-Research/commons/assets/103450846/bf17179c-e41f-492f-8148-a7ae6aba862e">

**Comment by babaklar** [comment]
When I select the "Create New Doc" in the HCommons group, the page refreshes to look like this: 
<img width="722" alt="Screenshot 2024-05-08 at 10 42 00 AM" src="https://github.com/MESH-Research/commons/assets/103450846/744113f3-aa2f-4aa0-8203-6dc2d5933d6f">

**Comment by babaklar** [comment]
Site creation on HASTAC and HCommons does not work. Clicking the link or "Visit Site" button always directs to hcommons.org homepage. The site shows up on profile but links do not work. I am not having issues accessing sites that were created previously. Additionally, the blog posts section is not showing up on hcommons.org profiles. I had a point where the profile showed a "critical Wordpress error" in the space where that section should be, but I wasn't able to replicate this. 

Another side note I'm noticing in a number of different contexts. At times, page formatting is wonky, but I'm not always able to duplicate more than once. For example, there was a point where the HASTAC nav menu was in the middle of the page, but I've only had it happen once.

**Comment by mikethicke** [comment]
> I'm having an issue loading HASTAC groups. When I go to the Groups directory, I get the below error message for all the HASTAC specific groups. When I refresh the page, it seems to resolve the error. However, at times it still appears after reloading the page. This looks specific to HASTAC groups and not replicable on the other group directories across the Commons.
> 
> Additionally, after creating a sample group, it is sometimes it is showing up here and sometimes it isn't. <img alt="Screenshot 2024-05-08 at 9 59 58 AM" width="1437" src="https://private-user-images.githubusercontent.com/103450846/328917431-11c41e26-3e6c-4737-b216-d26c88a08bc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjExMjIsIm5iZiI6MTcxNTI2MDgyMiwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTE3NDMxLTExYzQxZTI2LTNlNmMtNDczNy1iMjE2LWQyNmM4OGEwOGJjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzIwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODYzZWI3MTE0OTA1ZmUzM2Q2Yzk0NzY0MTE4MzI4M2FmMjI0YmI1YzcyMDQwZDdkMWYxOTYxMTNiMjIxMTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZkeNKNM9ZvHU1XQ8STz4GloWRwc-GpsKSBVKfp0U-G4">

This one should be fixed. Updated the Smart Slider 3 plugin.

**Comment by mikethicke** [comment]
> HASTAC CORE is not loading. This might not matter because of KC Works but still flagging here. CORE on other Commonses seems okay. <img alt="Screenshot 2024-05-08 at 10 06 10 AM" width="1439" src="https://private-user-images.githubusercontent.com/103450846/328919320-3cd3b504-b1ce-41c7-b9e9-7600d88a0afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjE0NDksIm5iZiI6MTcxNTI2MTE0OSwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTE5MzIwLTNjZDNiNTA0LWIxY2UtNDFjNy1iOWU5LTc2MDBkODhhMGFmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzA3MGNlNTgxODg2OTk5NTY4ZjczNjQ3M2ZkODc5YWM1NTg0NzczMWEwNTBmYzJmMTZiN2E5NmUwNWJkOTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.34E3gBhRlatxZo7DIsnf9qachU-Vg3NxdxpWWyxh4qk">

This was a connectivity issue with the library servers. Should be addressed now.

**Comment by mikethicke** [comment]
> There is a slight functionality issue I'm experiencing on the Sites page that affects toggling between "All Sites" and "My Sites." At times, instead of showing all sites, it is showing what should be listed as "My Sites" instead. Double clicking on All Sites fixes the issue. <img alt="Screenshot 2024-05-08 at 10 10 00 AM" width="1437" src="https://private-user-images.githubusercontent.com/103450846/328920410-a098b8dd-9fd6-407e-849f-4dcf0962e605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjE0NDksIm5iZiI6MTcxNTI2MTE0OSwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTIwNDEwLWEwOThiOGRkLTlmZDYtNDA3ZS04NDlmLTRkY2YwOTYyZTYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzhjMGQ3OTg3NzUxMDYyMzg3N2M3ZTJjMzRlOThiMTg0YThhNzg0Njk3Njk2MzkyNGIxNjI4ZTZjNWY5ZTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n2afxVC4SEX_L4ey6P4Q1Jl1YC4sHj8W7UCF3rSKCKQ">

I wasn't able to replicate this one. I suspect it is a timing issue in Javascript that probably exists in the current site as well.

**Comment by mikethicke** [comment]
> I am not able to edit my sample group site or manage my group's settings. I created a site when I made the group, but when I select "Site" from the group page, it takes me to the hcommons.org homepage. When I go to "Manage" on the group's menu, I get the following Wordpress error. I was able to duplicate this error on both HASTAC and HCommons. <img alt="Screenshot 2024-05-08 at 10 19 20 AM" width="1438" src="https://private-user-images.githubusercontent.com/103450846/328923421-6602a13e-bd45-463c-bc9e-759731b6037c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjE0NDksIm5iZiI6MTcxNTI2MTE0OSwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTIzNDIxLTY2MDJhMTNlLWJkNDUtNDYzYy1iYzllLTc1OTczMWI2MDM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDBlZjJmY2VmYWIxY2IyYmM5NDRmYzhkNmRmZTM0ZjRjYzA2ZDYwMDBjNzZlYzg3ODViZjk1NDkzM2E4ZDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LjwuXomPrAYJt77iSSrYogpgMCZV98e62jPFEXF_Jc8">

Successfully replicated. This looks like a PHP 8 compatibility issue in BuddyPress reply by email:

![image](https://github.com/MESH-Research/commons/assets/26980498/aabbdddf-3012-4a79-b768-c0b9b04ea0ee)

**Comment by mikethicke** [comment]
> Site creation on HASTAC and HCommons does not work. Clicking the link or "Visit Site" button always directs to hcommons.org homepage. The site shows up on profile but links do not work. I am not having issues accessing sites that were created previously. Additionally, the blog posts section is not showing up on hcommons.org profiles. I had a point where the profile showed a "critical Wordpress error" in the space where that section should be, but I wasn't able to replicate this.
> 
> Another side note I'm noticing in a number of different contexts. At times, page formatting is wonky, but I'm not always able to duplicate more than once. For example, there was a point where the HASTAC nav menu was in the middle of the page, but I've only had it happen once.

This is a permalinks rewrite issue. Flushing permalinks fixes the issue for existing sites. I haven't tested whether this will permanently fix the issue or whether permalinks need to be flushed each time a new site is created.

**Comment by mikethicke** [comment]
> When I select the "Create New Doc" in the HCommons group, the page refreshes to look like this: <img alt="Screenshot 2024-05-08 at 10 42 00 AM" width="722" src="https://private-user-images.githubusercontent.com/103450846/328931826-744113f3-aa2f-4aa0-8203-6dc2d5933d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjE0NDksIm5iZiI6MTcxNTI2MTE0OSwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTMxODI2LTc0NDExM2YzLWFhMmYtNGFhMC04MjAzLTZkYzJkNTkzM2Q2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjI3OTA0OWM4NjVjMmU1MGU3YWY1NDVhMjI4MDczNzkxYmUyZjA1OGI2MDc0NTNiYjQ4YmQ2Y2UzMTJhNzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mumYGXKEJjpLmC6OZY-QBbDEy2yQJirodm0ZGt4YVA4">

Doc creation should be working now. Tested with and without attachment.

**Comment by mikethicke** [comment]
> > I am not able to edit my sample group site or manage my group's settings. I created a site when I made the group, but when I select "Site" from the group page, it takes me to the hcommons.org homepage. When I go to "Manage" on the group's menu, I get the following Wordpress error. I was able to duplicate this error on both HASTAC and HCommons. <img alt="Screenshot 2024-05-08 at 10 19 20 AM" width="1438" src="https://private-user-images.githubusercontent.com/103450846/328923421-6602a13e-bd45-463c-bc9e-759731b6037c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjE0NDksIm5iZiI6MTcxNTI2MTE0OSwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTIzNDIxLTY2MDJhMTNlLWJkNDUtNDYzYy1iYzllLTc1OTczMWI2MDM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDBlZjJmY2VmYWIxY2IyYmM5NDRmYzhkNmRmZTM0ZjRjYzA2ZDYwMDBjNzZlYzg3ODViZjk1NDkzM2E4ZDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LjwuXomPrAYJt77iSSrYogpgMCZV98e62jPFEXF_Jc8">
> 
> Successfully replicated. This looks like a PHP 8 compatibility issue in BuddyPress reply by email:
> 
> ![image](https://private-user-images.githubusercontent.com/26980498/329262089-aabbdddf-3012-4a79-b768-c0b9b04ea0ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjE4NzIsIm5iZiI6MTcxNTI2MTU3MiwicGF0aCI6Ii8yNjk4MDQ5OC8zMjkyNjIwODktYWFiYmRkZGYtMzAxMi00YTc5LWI3NjgtYzBiOWIwNGVhMGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEzMzI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MWU4ZTdjZGQ0N2RhMTg5ZDhjMGIzNDQ1NDI0ZDBkOTFlMjU5MjFjZTJiZjhkOWE5ZDdkNDUwNzcxMGJiY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wCh4Y4rwdLr9EVTaKfZsP4vPYQ9JTvcwIZXuIBgqqmY)

Should be fixed.

**Comment by mikethicke** [comment]
> In my sample group, I am not able to upload or view files. Similar to what Bonnie reported, all groups with files show a number on the groups nav menu, but when I click on the page, there is nothing listed. This is what it looks like for me, and I cannot upload files here either.
> 
> <img alt="Screenshot 2024-05-08 at 10 33 07 AM" width="1439" src="https://private-user-images.githubusercontent.com/103450846/328928530-8a90c094-e52c-4504-a41b-f2502d54d637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjE0NDksIm5iZiI6MTcxNTI2MTE0OSwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTI4NTMwLThhOTBjMDk0LWU1MmMtNDUwNC1hNDFiLWYyNTAyZDU0ZDYzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWJjZWU1Y2M3MWI0M2U2MDBlODFjZDc5NmE5NzA3OGQ5MTdmMTBjMzQxNWRmNDM2OTRhZWU4NDk1MGFlMjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6-LLty87Y7BQ4KfoQIC3n4fry4mNADERx8LGcTlCOjE">
> This same issue occurs for me on HASTAC group docs. I'm having a different issue with HCommons docs I will add a different comment for.
> 
> <img alt="Screenshot 2024-05-08 at 10 40 47 AM" width="1439" src="https://private-user-images.githubusercontent.com/103450846/328931278-bf17179c-e41f-492f-8148-a7ae6aba862e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjE0NDksIm5iZiI6MTcxNTI2MTE0OSwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTMxMjc4LWJmMTcxNzljLWU0MWYtNDkyZi04MTQ4LWE3YWU2YWJhODYyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzI1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDNkODYwNjU3ZWUyYmQ1ODg5ODE4ZDEyNTM5ZDA3ZGQ2YTc3NWFjNGM5YWNkZDNjOGM2MWYyODkzZjdlOGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-WyBLWx-mjA3H1Ns7YZgL4CVh9VKgg-fa4ZEk3mTc1U">

The upload form is working now, but it appears that files are failing to actually upload.

**Comment by babaklar** [comment]
I'm still not able to manage group settings. [Uploading... Screenshot 2024-05-14 at 9.51.01 AM.png]

**Comment by babaklar** [comment]
File uploads are also still not working. I was able to get to the upload form, but uploading just refreshed the page and nothing happened. When I clicked again on the Files link at the top of the page, I received a message saying "there are no uploads."

**Comment by mikethicke** [comment]
> In my sample group, I am not able to upload or view files. Similar to what Bonnie reported, all groups with files show a number on the groups nav menu, but when I click on the page, there is nothing listed. This is what it looks like for me, and I cannot upload files here either.
> 
> <img alt="Screenshot 2024-05-08 at 10 33 07 AM" width="1439" src="https://private-user-images.githubusercontent.com/103450846/328928530-8a90c094-e52c-4504-a41b-f2502d54d637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTg2MDgsIm5iZiI6MTcxNjU1ODMwOCwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTI4NTMwLThhOTBjMDk0LWU1MmMtNDUwNC1hNDFiLWYyNTAyZDU0ZDYzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMzQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTRkNTdiYjM5YzUyYjRhMzg4OTgzYjAyYmUwOGVkZmVjNzJiMjAxNmFlNzlkOTQ0Y2FkNWNkODI3OWQyOTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wc7quucTUBs2ckPI-4avfR_0CDz5hACDr5W4GivP3MQ">
> This same issue occurs for me on HASTAC group docs. I'm having a different issue with HCommons docs I will add a different comment for.
> 
> <img alt="Screenshot 2024-05-08 at 10 40 47 AM" width="1439" src="https://private-user-images.githubusercontent.com/103450846/328931278-bf17179c-e41f-492f-8148-a7ae6aba862e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTg2MDgsIm5iZiI6MTcxNjU1ODMwOCwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTMxMjc4LWJmMTcxNzljLWU0MWYtNDkyZi04MTQ4LWE3YWU2YWJhODYyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMzQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjUyMWVlYjA4MzAwZDFjMjY0OTA0OGY3Y2JhZGJjY2NmYTQ3N2EzMmQwZjI4NzdjNDI0OTk5ODM0ZmZhMGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YYD0UEteT4LYtpZMUKl9Nkvteox3il0Akfk_voMAnHE">

Addressed by https://github.com/MESH-Research/knowledge-commons-wordpress/commit/22afc1cc477713d5d38dd5e89280165ca993d474

**Comment by mikethicke** [comment]
> I am not able to edit my sample group site or manage my group's settings. I created a site when I made the group, but when I select "Site" from the group page, it takes me to the hcommons.org homepage. When I go to "Manage" on the group's menu, I get the following Wordpress error. I was able to duplicate this error on both HASTAC and HCommons. <img alt="Screenshot 2024-05-08 at 10 19 20 AM" width="1438" src="https://private-user-images.githubusercontent.com/103450846/328923421-6602a13e-bd45-463c-bc9e-759731b6037c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTg2MDgsIm5iZiI6MTcxNjU1ODMwOCwicGF0aCI6Ii8xMDM0NTA4NDYvMzI4OTIzNDIxLTY2MDJhMTNlLWJkNDUtNDYzYy1iYzllLTc1OTczMWI2MDM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMzQ1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGNiYmU4NzcxYjY1NzYxMDI5MDZmNzE0MWQ2MjM3MjYwYTJlZDM2NmEwZmUxNzYzNjliZmUzYzA0MTcwOWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TqA-eKdoOPSj2dHki_QLi0oaGJGMP18CrhVU_oLW7Pc">

This should be fixed.

**Comment by mikethicke** [comment]
Review:

- [x] HASTAC groups not showing up
- [x] HASTAC CORE not loading
- [ ] Sites UI weirdness (Not fixing ATM. Could not replicate.)
- [x] Edit group settings
- [x] Visit group site
- [x] Doc creation
- [x] Site creation
- [x] File uploads

**Comment by bjr70** [comment]
We have a new issue on Group Docs - when you add an attachment it doesn't allow you to add a title or any metadata. It just reloads the page. This is a big deal for the MLA folks who use Docs for their journal workflow. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d7931c600f4d4b0ca19a2b443fd8e82c56c79a7/DocsAttachment.mp4)

**Comment by bjr70** [comment]
When going to manage group settings I'm still getting a critical error: https://hcommons.org/groups/br-test-group-container-1/admin/edit-details/

<img width="1771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3RQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b191e4bb2336326d75686ebee07772a9b9f8fa4f/criticalerror.png" alt="criticalerror.png" />

**Comment by bjr70** [comment]
File uploads to groups are not accessible. They do not load.

**Comment by bjr70** [comment]
Video of odd behavior and locking of the browser. Tried to capture errors. YouTube video here but being processed: [https://youtu.be/Ndk0iGomNlc](https://youtu.be/Ndk0iGomNlc)

**Comment by babaklar** [comment]
I am having issues with full site editing on sites. Like Bonnie, I made a video to capture the errors. To summarize, I can't use the block editor, and even after turning on full site editing, it didn't make a difference. 
[Uploading... Screen Recording 2024-06-11 at 11.57.12 AM.mov]

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a00a5909f53dc3ae03c3a7f27dcd4546913cbefa/Screen%20Recording%202024-06-11%20at%2011.57.12%E2%80%AFAM.mov)

**Comment by babaklar** [comment]
More follow up: I was able to access full site editing through both "Edit Site" and "Customize" on the site's admin menu. However, in both cases, the builder is acting wonky. For example, I was able to get to the point of adding an image on the page. However, the options for what image to upload or select from the media library doesn't appear. Then, when it did appear, it moved the image upload option to the bottom of the page, not where the image was on the screen. I had a similar issue when adding an additional block.

I also am not able to view the live version of the site I created after saving changes. Selecting "View site" is taking me to the Knowledge Commons homepage. This same issue happens when you try to preview a page or post.

**Comment by babaklar** [comment]
More follow up: I was able to access full site editing through both "Edit Site" and "Customize" on the site's admin menu. However, in both cases, the builder is acting wonky. For example, I was able to get to the point of adding an image on the page. However, the options for what image to upload or select from the media library doesn't appear. Then, when it did appear, it moved the image upload option to the bottom of the page, not where the image was on the screen. I had a similar issue when adding an additional block.

I also am not able to view the live version of the site I created after saving changes. Selecting "View site" is taking me to the Knowledge Commons homepage.

**Comment by babaklar** [comment]
The featured image on this page is grayed out. The image I uploaded was the regular loaded--it didn't have gray shading. 

<img width="1529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWhUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5946fa6749512a288c8e17607140887402bdb053/Screenshot%202024-06-11%20at%2012.22.55%E2%80%AFPM.png" alt="Screenshot 2024-06-11 at 12.22.55 PM.png" />

**Comment by mikethicke** [comment]
I think there might be some wonkiness with routing between production and staging, but this does seem to be working for me. The greyed-out image probably indicates the image is still uploading, or that uploading was paused / interrupted. When I initially added an image I got some errors but subsequently it worked correctly.

**Comment by mikethicke** [comment]
Ok, actually editing a post seems deeply broken.

**Comment by mikethicke** [comment]
This works correctly on hcommons-dev.org, which is also running the containerized system. I think there must be some background request that is not being routed correctly and is screwing with the block editor.

**Comment by babaklar** [comment]
Blog posts are not showing up on user profiles on Knowledge Commons. I looked at my profile and Bonnie's, and in both cases there was no block.

**Comment by babaklar** [comment]
I am not able to log into "admin only" sites I've created in the past. I tried this with both MSU and ORCID authentication. In both cases, after I enter in my username and password, the login page continually reloads and cycles around. Here's a video of what's happening: 
[Uploading... Screen Recording 2024-06-11 at 2.31.51 PM.mov]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ZVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d44ac53f023b56f3121a4fee47a4fe258fa4101e/Screen%20Recording%202024-06-11%20at%202.31.51%E2%80%AFPM.mov)

**Comment by babaklar** [comment]
A similar issue happens with my HCID as well. After I log in, this page continually reloads.

<img width="1436" alt="Screenshot 2024-06-11 at 2 37 31 PM" src="https://github.com/MESH-Research/commons/assets/103450846/e25d6c22-589b-49e4-92c5-793afb285053">

**Comment by bjr70** [comment]
Ferdinand Test (non-privileged user) does not have "my groups" though he belongs to one. 
<img width="1489" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05VQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--810d9e17b4a7864dbc07800d3ae9fa3e4de83647/No%20My%20Groups.png" alt="No My Groups.png" />

**Comment by bjr70** [comment]
Replying and adding an attachment to a discussion post breaks the page and locks it. Can't reload, click out, or otherwise get out. The entire browser is locked up again and I have to force quit. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--918a9d01e5527004a61cf0b3d47af6edf54c700d/BrokenGroupPage.png" alt="BrokenGroupPage.png" />

**Comment by bjr70** [comment]
Something about the file upload dialogue in groups (files, forum, docs attachments) seems to lock up the browser. It's either when trying to upload or after the upload. It also locks up when you try to access files, but that one seems intermittent. There's something that's not firing right. I've just had Chrome lock up on my twice in about 10 minutes. Both around file uploads. In some cases you choose a file to upload and it just fails to respond and eventually locks up the browser. It looks like there may be some sort of bug in it. 

When I did get to choose a file it hung on a 15kb file. I'm on a gigabit connection with no speed issues. No weird plugins on Chrome. <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUZWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--78acc411cde869abc63387f9641b0137c540d058/hungon15kbfile.png" alt="hungon15kbfile.png" />

**Comment by babaklar** [comment]
Some of the files uploaded in CORE are not available. When you click on a deposit, you receive the below error message. All of the fields below Metadata ("published as" "status" "last updated" "license" "downloads" and "activity") do not appear. 

It looks like this _might_ just be deposits that were very recently uploaded--clicking through, anything sooner than at least 5 days ago. Some of my older deposits are fine. 

The message is: "Note: There is a problem retrieving some of the data for this item. This error has been logged." <img width="1725" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVZWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ab5104c6849f54493b57b617400eaf496ee1c4c/Screenshot%202024-06-11%20at%204.02.38%E2%80%AFPM.png" alt="Screenshot 2024-06-11 at 4.02.38 PM.png" />

**Comment by mikethicke** [comment]
- [x] Block editor doesn't work correectly
- [x] Blog posts don't show up on profiles
- [x] Can't log into old admin-only sites
- [x] Layout issues in forums
- [x] Problems uploading file attachments in groups
- [ ] Recent CORE uploads not working

**Comment by babaklar** [comment]
The formatting of the "Files" page is not correct--the upload files page is directly underneath uploaded files. On prod, these are separate pages.

<img width="1800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVIzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2001260092eb8cb41f2c6bf47a770e641b87edd7/Screenshot%202024-06-19%20at%2010.27.41%E2%80%AFAM.png" alt="Screenshot 2024-06-19 at 10.27.41 AM.png" />

There is additional weird formatting on HASTAC Commons--"Files" are listed as "Documents."<img width="1804" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWgzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2641b21a52e5e181c3d8252c254296195f7b6553/Screenshot%202024-06-19%20at%2010.29.09%E2%80%AFAM.png" alt="Screenshot 2024-06-19 at 10.29.09 AM.png" />

**Comment by mikethicke** [comment]
<img width="1256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cca7425e7ce422282097a2748f570f78bc173dd9/image.png" alt="image.png" />

On prod there is a "Upload New Document" button that unhides the upload form when clicked. Must be a Javascript issue.

**Comment by bjr70** [comment]
Testing complete.
