### ISSUE TITLE
Can't upload files or images to MLA Commons groups, can't create docs, can't edit sites as admin

### ISSUE THREAD

**Issue by bjr70** [mlaa/commons#905]
Tried in the create a group process for Kelly Test Group. When trying to upload a group photo I got this error: Upload Failed! Error was: Unable to create directory 1004670/group-avatars/1004670. Is its parent directory writable by the server?

When trying to upload a cover image I just got "HTTP error."

When trying to create a doc I get a blank screen - same error as the missing content. "Response was blocked by CORB"

https://mla.hcommons.org/groups/kelly-test-group/docs/

Can't edit group site: https://kellytestgroup.mla.hcommons.org/wp-login.php?redirect_to=https%3A%2F%2Fkellytestgroup.mla.hcommons.org%2Fwp-admin%2Fthemes.php&reauth=1

**Comment by mikethicke** [comment]
Currently the group page is completely blank when I visit it:

<img width="1060" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71a1e189510a74e21c0bc2b68ee7c183bdef7d35/Screenshot%202024-06-15%20at%207.31.31%E2%80%AFAM.png" alt="Screenshot 2024-06-15 at 7.31.31 AM.png" />

**Comment by mikethicke** [comment]
I believe these are addressed

**Comment by bjr70** [comment]
The group still shows as blank for me in a private window on Facebook (ignore the weird glitch, I used Snagit and it scrolled): 
![blankgroupmla0617](https://github.com/MESH-Research/commons/assets/11507407/75ec98bc-aa2a-4058-8670-59a9c94e87c0)

**Comment by bjr70** [comment]
All groups are blank on MLA whether logged in or logged out (for public groups).

**Comment by bjr70** [comment]
Kelly Test is expired on SAH, but the groups do show up. This may be a weird MLA thing.

**Comment by bjr70** [comment]
Was the CBOX-Auth plugin. Solved.
